# example netlify.toml
[build]
  command = "pnpm --filter react-resize-bounding... run build && pnpm --filter react-resize-bounding... run docs:build"
  functions = "netlify/functions"
  publish = "storybook-static"

  [[redirects]]
    from = "/*"
    status = 200
    
  [[headers]]
    for = "/*"
    [headers.values]
      Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
