import fs from "node:fs";
import tinycolor from "tinycolor2";

interface ColorsGeneratorOptions {
  source: string;
  outDir: string;
  variations?: number;
  maxVar?: number;
  comment?: string;
}

interface Colors {
  [key: string]: string;
}

interface ColorStrategy {
  manipulate(color: string, percent: number): string;
}

class DarkenStrategy implements ColorStrategy {
  manipulate(color: string, percent: number): string {
    return tinycolor(color).darken(percent).toHexString();
  }
}

class LightenStrategy implements ColorStrategy {
  manipulate(color: string, percent: number): string {
    return tinycolor(color).lighten(percent).toHexString();
  }
}

export class ColorsGenerator {
  private static instance: ColorsGenerator;
  private temp: Colors = {};
  private variations: number;
  private maxVar: number;
  private comment: string;

  constructor(public opts: ColorsGeneratorOptions) {
    const {
      source,
      outDir,
      variations = 20,
      maxVar = 45,
      comment = `# ${opts.outDir} Generated by colorsGenerator. !! DO NOT MODIFY THIS FILE !!\n`,
    } = opts;
    this.variations = variations;
    this.maxVar = maxVar;
    this.comment = comment;
    this.loadSourceFile(source, outDir);
  }

  public static getInstance(opts: ColorsGeneratorOptions): ColorsGenerator {
    if (!ColorsGenerator.instance) {
      ColorsGenerator.instance = new ColorsGenerator(opts);
    }
    return ColorsGenerator.instance;
  }

  get mid() {
    return Math.round(this.variations / 2);
  }

  get dist() {
    return Math.round(this.mid - 1);
  }

  get step() {
    return this.maxVar / this.dist;
  }

  private toKebabCase(key: string): string {
    return key
      .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
      .replace(/([A-Z])([A-Z])(?=[a-z])/g, "$1-$2")
      .toLowerCase();
  }

  private loadSourceFile(source: string, output: string) {
    if (!/^(?=.).*.json$/.test(source))
      throw new Error("Invalid source file (should be a JSON file)");
    const file = fs.readFileSync(source, "utf-8");

    this.listColors(JSON.parse(file));
    const colors: Colors = this.temp;
    this.writeOutputFile(JSON.stringify(colors), output);
  }

  private writeOutputFile(data: string, output: string): void {
    try {
      fs.writeFileSync(output, data);
      fs.writeFileSync(output.replace(/.json$/, ".md"), this.comment);
      console.log(`Colors generated to the ${output}`);
    } catch {
      console.log("Error while writing generated colors");
    }
  }

  private listColors(colors: Colors) {
    for (const [k, v] of Object.entries(colors)) {
      if (typeof v === "string") {
        this.temp = {
          ...this.temp,
          ...this.generateColors(this.toKebabCase(k), v),
        };
      } else if (typeof v === "object" && v !== null) {
        this.listColors(v);
      }
    }
  }

  private generateColors(name: string, color: string) {
    const temp: [string, string][] = [];

    for (let i = 0; i < this.variations; i++) {
      const percent = this.maxVar - this.step * (i - 1) * 1;
      const darken =
        ((this.variations - i) * 1000) / Math.round(this.variations);
      const lighten = (i * 1000) / Math.round(this.variations);

      temp.push([
        `${name}-${darken}`,
        this.applyStrategy(new DarkenStrategy(), color, percent),
      ]);

      temp.push([
        `${name}-${lighten}`,
        this.applyStrategy(new LightenStrategy(), color, percent),
      ]);
    }

    const sorted = temp.sort((a: [string, string], b: [string, string]) => {
      const numA = Number(a[0].split("-")[1]);
      const numB = Number(b[0].split("-")[1]);

      return numA - numB;
    });

    const map: Colors = {};
    sorted.map(([key, value]) => {
      map[key] = value;
    });

    return map;
  }

  private applyStrategy(
    strategy: ColorStrategy,
    color: string,
    percent: number,
  ): string {
    return strategy.manipulate(color, percent);
  }
}
